apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-deployments
spec:
  generators:
    - git:
        repoURL: https://gitlab.com/Boudreaux-labs/app-deploy.git
        revision: main
        directories:
          - path: ghost
          #- path: another-app eventually
  template:
    metadata:
      name: '{{path.basename}}'  # App name derived from directory name
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/Boudreaux-labs/app-deploy.git
        targetRevision: main
        chart: '{{path.basename}}'  # Matches the folder name
        helm:
          valuesFiles:
          - values.yaml                      # Default values in chart directory
          - overrides.yaml
          ignoreMissingValueFiles: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'         # Namespace matches folder name
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
       

