apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-deployments
spec:
  generators:
    - git:
        repoURL: https://gitlab.com/Boudreaux-labs/app-deploy.git
        revision: main
        directories:
          - path: ghost
          #- path: another-app
  template:
    metadata:
      name: '{{path.basename}}'  # App name derived from directory name
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/Boudreaux-labs/app-deploy.git
        targetRevision: main
        chart: '{{path.basename}}'  # Matches the folder name
        helm:
          valuesFiles:
            - values.yaml                      # Default values in chart directory
            #- ../../argo_config/overrides.yaml # Uncomment for external overrides
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'         # Namespace matches folder name
        createNamespace: true                  # Automatically create namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
