apiVersion: v1
kind: Secret
metadata:
  name: boudreaux-labs-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/boudreaux-labs/
