server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/certificate-arn: "${cert_arn}"
      alb.ingress.kubernetes.io/inbound-cidrs: "${my_ip}"
      external-dns.alpha.kubernetes.io/hostname: argocd-dev.boudreauxlabs.com
      
  paths:
    - /* 
  tls:
  - hosts:
    - argocd-dev.boudreauxlabs.com
  service:
    type: NodePort


  # # -- ArgoCD rbac config ([ArgoCD RBAC policy])
  # ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
  # rbacConfig:
  #   {}
  #   # policy.csv is a file containing user-defined RBAC policies and role definitions (optional).
  #   # Policy rules are in the form:
  #   #   p, subject, resource, action, object, effect
  #   # Role definitions and bindings are in the form:
  #   #   g, subject, inherited-subject
  #   # See https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md for additional information.
  #   # policy.csv: |
  #   #   # Grant all members of the group 'my-org:team-alpha; the ability to sync apps in 'my-project'
  #   #   p, my-org:team-alpha, applications, sync, my-project/*, allow
  #   #   # Grant all members of 'my-org:team-beta' admins
  #   #   g, my-org:team-beta, role:admin
  #   # policy.default is the name of the default role which Argo CD will falls back to, when
  #   # authorizing API requests (optional). If omitted or empty, users may be still be able to login,
  #   # but will see no apps, projects, etc...
  #   # policy.default: role:readonly
  #   # scopes controls which OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
  #   # If omitted, defaults to: '[groups]'. The scope value can be a string, or a list of strings.
  #   # scopes: '[cognito:groups, email]'

  # # -- Annotations to be added to ArgoCD rbac ConfigMap
  # rbacConfigAnnotations: {}

  # # -- Whether or not to create the configmap. If false, it is expected the configmap will be created
  # # by something else. ArgoCD will not work if there is no configMap created with the name above.
  # rbacConfigCreate: true