server:
  ingress:
    enabled: true
    ingressClassName: alb
    hostname: ${argocd_url}
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: "${cert_arn}"
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
      alb.ingress.kubernetes.io/success-codes: "200"
      alb.ingress.kubernetes.io/inbound-cidrs: "${my_ip}"
      external-dns.alpha.kubernetes.io/hostname: ${argocd_url}
    tls: false

configs:
  params:
    server.insecure: false
