server:
  additionalApplications:
   - name: cluster-addons
     namespace: argocd
     project: default
     source:
       repoURL: https://gitlab.com/boudreaux-labs/app-deploy
       targetRevision: HEAD
       path: addons
       directory:
         recurse: true
     destination:
       server: https://kubernetes.default.svc
     syncPolicy:
       automated:
         prune: false
         selfHeal: false
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: instance
      external-dns.alpha.kubernetes.io/hostname: ${argocd_url}
    ingressClassName: alb
  service:
    type: NodePort