#A pipeline thats a combination from stuff I saw at work and my own desire to have all my terraform build as an IAM role that Gitlab assumes (hence the token stuff)

image:
  name: "registry.gitlab.com/gitlab-org/terraform-images/releases/1.5"

variables:
  TF_ROOT: ${ENVIRONMENT}  # The relative path to the root directory of the Terraform project
  TF_STATE_NAME: default      # The name of the state file used by the GitLab Managed Terraform state backend

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

#This runs before the 'script block in every job below. It sets the Profile and Web Identity Token, within the AWS config file.
#For this to work you also need to set a Gitlab CICD variable of 'AWS_PROFILE' with a value of 'oidc'. This takes the place of key CICD variables
#We do this so that Gitlab's deployments to AWS occur as the IAM role, not the CICD user. Best security practice and allows someone to us the role and get right into EKS without configmap changes
#default:
#  before_script: 
#  - mkdir -p ~/.aws
#  - echo "${MY_OIDC_TOKEN}" > /tmp/web_identity_token
#  - echo -e "[profile oidc]\nrole_arn=${ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config
# - cat ~/.aws/config
# - apk add aws-cli
# - export AWS_PROFILE=oidc
#  - ARGO_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ArgoAdminPassword --query SecretString --output text | jq -r '.ArgoAdminPassword')
#  - export ARGO_PASSWORD

.id_token: &id_token
    id_tokens:
      MY_OIDC_TOKEN:
        aud: https://gitlab.com

default:
  before_script: 
  - mkdir -p ~/.aws
  # Install necessary tools
  - apk add --no-cache aws-cli jq

  # Configure AWS profile for OIDC role assumption
  - echo "${MY_OIDC_TOKEN}" > /tmp/web_identity_token
  - echo -e "[profile oidc]\nrole_arn=${ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config
  - cat ~/.aws/config
  - export AWS_PROFILE=oidc

  # Retrieve the ArgoCD admin password from AWS Secrets Manager
  #- echo "MY_OIDC_TOKEN length is ${#MY_OIDC_TOKEN}"
  - echo reading token...
  - cat $MY_OIDC_TOKEN
  - cat /tmp/web_identity_token
  - echo "Retrieving ARGO_PASSWORD..."
  - ARGO_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ArgoAdminPassword --query SecretString --output text | jq -r '.ArgoAdminPassword')
  - echo "ARGO_PASSWORD successfully retrieved."
  - export ARGO_PASSWORD


stages:
  - validate
  - plan
  - apply
  - destroy
  
.artifacts: &artifacts
    artifacts:
      name: plan
      paths:
      - ${TF_ROOT}/plan.cache
      - ${TF_ROOT}/plan.json
      reports:
        terraform: ${TF_ROOT}/plan.json

dev-validate: 
  stage: validate
  script:
    - cd dev
    - gitlab-terraform init
    - gitlab-terraform validate
  variables:
    ENVIRONMENT: dev    


dev-plan: 
  stage: plan
  script:
    - cd dev
    - gitlab-terraform init
    - gitlab-terraform plan -var="argocd_admin_password=$ARGO_PASSWORD" -auto-approve
    - gitlab-terraform plan-json
  variables:
    ENVIRONMENT: dev  
  <<: *artifacts
  <<: *id_token


dev-apply: 
  stage: apply
  script:
    - cd dev
    - gitlab-terraform init
    - gitlab-terraform apply -var="argocd_admin_password=$ARGO_PASSWORD" -auto-approve
  when: manual
  variables:
    ENVIRONMENT: dev  
  <<: *artifacts
  <<: *id_token


dev-destroy: 
  stage: destroy
  script:
    - cd dev
    - gitlab-terraform init
    - gitlab-terraform destroy -var="argocd_admin_password=$ARGO_PASSWORD" -auto-approve
  when: manual
  variables:
    ENVIRONMENT: dev  
  <<: *artifacts
  <<: *id_token
 
