apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-deployments
spec:
  generators:
    - git:
        repoURL: https://gitlab.com/Boudreaux-labs/app-deploy.git
        revision: main
        directories:
          - path: ghost
          #- path: another-app
  template:
    metadata:
      name: '{{path.basename}}'  # App name suffixed with environment
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/Boudreaux-labs/app-deploy.git
        targetRevision: main
        chart: '{{path.basename}}'
        helm:
          valuesFiles:
            - values.yaml           # Default values from the app-deploy repo
            #- ../../argo_config/overrides.yaml  # Environment-specific overrides
      destination:
        server: https://kubernetes.default.svc
        #namespace: '{{path.basename}}'
        namespace: 'argoocd'
        createNamespace: true   # Auto-create the namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
