name: destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: dev
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          export TF_VAR_ci_role_arn="${{ vars.ROLE_ARN }}"
          export TF_VAR_argocd_admin_password="$(aws secretsmanager get-secret-value --secret-id ArgoAdminPassword --query SecretString --output text | jq -r '.ArgoAdminPassword')"
          terraform destroy -auto-approve
